# Generated by Django 4.0.5 on 2022-07-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='queen',
            name='category',
            field=models.ManyToManyField(to='main_app.category'),
        ),
    ]
